# Generated by Django 3.2.6 on 2021-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Hortifruti', 'H'), ('Carnes', 'C'), ('Frios', 'F'), ('Utensilos', 'U')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
