# Generated by Django 3.2.6 on 2021-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210827_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('H', 'Hortifruti'), ('C', 'Carnes'), ('F', 'Frios'), ('U', 'Utensilos')], max_length=10),
        ),
    ]
