# Generated by Django 3.2.6 on 2021-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210827_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=2, upload_to='media/'),
            preserve_default=False,
        ),
    ]
